### ISSUE TITLE
Show the value of the created column in the table for pending community requests

### ISSUE THREAD

**Issue by astump** [StarExec/StarExec#206]
On both the admin and the communities page, there is a table showing pending community requests.  In order (for admins and community leaders) to keep track better of these, it would be helpful to see the date the request was created, as part of the table.

This was raised by @tinelli.

**Comment by pathawks** [comment]
As a starting point, here is the code that handles requests for pending community requests
https://github.com/StarExec/StarExec/blob/ddacc3381b31af9a617f2132ff102fbfc4ce10d3/src/org/starexec/app/RESTServices.java#L4430-L4442
