### ISSUE TITLE
Investigate slow download speed for job output

### ISSUE THREAD

**Issue by astump** [StarExec/StarExec#236]
Martin Suda tells us (on email):

> I am still a bit curious whether you had a change to look at the download speed. The way I do my batching with this experiment makes my output files roughly 350MB each. This sometimes takes several hours to download which gets inconvenient when I need to take my laptop and leave (which terminates the download). Again, this is not urgent in principle, but if you don't know why it is so slow, investigating it might point you to a source of inefficiency in the whole infrastructure (my guess).

**Comment by astump** [comment]
@quickbeam123, we are going to look into this.  It looks like any of your recent rather large jobs exhibit this behavior, like https://www.starexec.org/starexec/secure/details/job.jsp?id=32233

**Comment by Swisty** [comment]
We're looking into this now. It appears as if there is a command run for each downloaded file on our end that is eating up a lot of time. We are in the midst of testing to be sure that removing the offending line does not majorly affect the downloaded files.

**Comment by astump** [comment]
We just deployed a change that @Swisty made which we hope will improve download speed.  @Swisty , you can try out some example now on StarExec and see if things seem better.  @quickbeam123, you could also try this and let us know what you observe...  Thanks!

**Comment by quickbeam123** [comment]
Hi, it seemed to be an improvement in the beginning. I was getting up to 500KB/s (I am in Vienna.) But now I am also seeing less than 10KB/s which is not that good.
