### ISSUE TITLE
Add ability to upload benchmarks via git clone

### ISSUE THREAD

**Issue by astump** [StarExec/StarExec#270]
We would like to allow users to upload benchmarks by specifying a URL to use for a git clone.

**Comment by astump** [comment]
Mathias Preiner tells us:

The SMT-LIB git repositories use git LFS (https://git-lfs.github.com/)
to store large files in a repository. On the server side you have to
make sure that git lfs is installed, otherwise the benchmarks tracked
via LFS are not correctly cloned.

**Comment by mpreiner** [comment]
The server providing the files doesn't have to zip the whole repository, which can take some time for big repositories. Additionally, git has better error handling/integrity checks. If something goes wrong while cloning the repository git will tell you and you won't end up with an inconsistent state/missing benchmarks.

**Comment by sfiolic** [comment]
The Git clone upload feature is now on StarExec.org. To use, navigate to a space you want to upload your benchmarks and click the upload benchmark button like before for other upload methods. There is a new checkbox `Git`, select it and enter the web URL of your repositor in the text box below. This will clone a Git repository to the StarExec space after submitting request. README.md, .gitattributes, and .gitignore files will be ignored if in the selected Git repository, those files are ok to have in repository. Please refrain from including other files than benchmarks and description files in the Git repository.
