### ISSUE TITLE
libstdc++

### ISSUE THREAD

**Issue by ekgma** [StarExec/StarExec#274]
When running one of my solvers I get the following errors:

/lib64/libstdc++.so.6: version ‍GLIBCXX_3.4.20 not found
/lib64/libstdc++.so.6: version CXXABI_1.3.8 not found 
/lib64/libstdc++.so.6: version GLIBCXX_3.4.21 not found

this is an external tool I'm using and I don't have access to the source to recompile.

**Comment by astump** [comment]
You can see information on the basic software available on StarExec here:

https://www.starexec.org/starexec/public/machine-specs.txt

It looks like the binary you have is expecting a more recent glibc than we have installed.  We will not be able to upgrade glibc to support this.  Sorry about that.
