### ISSUE TITLE
web interface: "do you want to make this space public" does not show which space

### ISSUE THREAD

**Issue by jwaldmann** [StarExec/StarExec#289]
also the confirmation does not mention the space's name

**Comment by gg9192** [comment]
Here is whats implemented so far. I am assuming that the original author wants something like: Do you want to make only ____ pubic, or ______ and all subspaces?

<img width="1440" alt="Screenshot 2023-07-17 at 15 13 00" src="https://github.com/StarExec/StarExec/assets/42902579/8d35777d-371b-441c-bfd7-83a0c56e88b6">

**Comment by gg9192** [comment]
I have fixed this issue, here is the new UI:
<img width="1440" alt="Screenshot 2023-07-17 at 15 43 46" src="https://github.com/StarExec/StarExec/assets/42902579/e4f8eaff-4cf9-4d74-9943-b3057f01e785">

**Comment by gg9192** [comment]
https://github.com/StarExec/StarExec/pull/369
