### ISSUE TITLE
web interface: after creating a job, should not return to root

### ISSUE THREAD

**Issue by jwaldmann** [StarExec/StarExec#293]
I am viewing a space. I create a job there. When the job is submitted, I get bumped to the (un-expanded) view of the root space. I expect to return to where I was before. 

It's no big deal, but navigation (in the "space" column) is slow (one second per click or more - enough time to show a spinning wheel)

**Comment by AkihisaYamada** [comment]
Hi! I would appreciate very much if we are forwarded to the created job.

**Comment by gg9192** [comment]
This should be relatively simple to fix.

**Comment by gg9192** [comment]
https://github.com/StarExec/StarExec/pull/368/files

**Comment by AkihisaYamada** [comment]
Thank you, this makes the work of running competition much easier!
I had to browse to find the jobid whenever I create a job but now it's instant :)

**Comment by gg9192** [comment]
No problem. We deployed this, and a whole bunch of other fixes yesterday.
Thanks,
Alex Guo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
