### ISSUE TITLE
Failed to upload a benchmark (negative number of bytes remaining)

### ISSUE THREAD

**Issue by inpefess** [StarExec/StarExec#299]
I try to upload a small benchmark file but get the following message:

```
The benchmark upload is too large to fit in your disk quota. The uncompressed size of the archive is approximately 122880 bytes, but you have only -1442810058 bytes remaining.
```

**Comment by astump** [comment]
Sorry for the broken error message (and thanks for filing a bug report on
that).

I increased your quota, so that will solve your own issue I hope for now.

Aaron
