### ISSUE TITLE
Web interface: `All` buttons do not work

### ISSUE THREAD

**Issue by vuphan314** [StarExec/StarExec#300]
Hello, @astump,

On the web interface, the `All` buttons do not appear to work.

For example, please see this screenshot of a public [space](https://www.starexec.org/starexec/secure/explore/spaces.jsp?id=9256):
![Screenshot from 2021-05-09 16-31-44](https://user-images.githubusercontent.com/12940605/117587543-15d14380-b0e4-11eb-92c3-0bb125b321ae.png)

I would like to select all benchmarks (to drag and drop into my user space). But when I click the `All` button under `benchmarks`, nothing happens.

Please help. Thank you.

**Comment by astump** [comment]
Very sorry!  I see you are right.  We will investigate and try to fix --
but it will probably be in June.
Thanks for letting me know,
Aaron

**Comment by vuphan314** [comment]
Prof. Stump,

The `All` button still appears to be broken:

![Screenshot from 2022-04-28 21-06-58](https://user-images.githubusercontent.com/12940605/165875000-e55713c4-4262-40e3-b5b7-ed6e5642fa1a.png)

If that is hard to fix, I would appreciate another way to select multiple items, for example:
1. click the first item
2. click the last item while holding `shift`

Thank you!

**Comment by astump** [comment]
Sorry, Vu!  I am hoping to hire a student to help work on StarExec this
summer, and I will have that person look at this.
Best,
Prof. Stump

**Comment by gg9192** [comment]
Hello sir,

I hope this finds you well. My name is Alex Guo, and I am the student engineer assigned to work on this ticket. I wanted to inform you about my approach to managing and updating tickets for better collaboration and progress tracking.

Typically, I make frequent updates and comments on tickets to ensure that I have a clear understanding of the tasks at hand and to provide a space for Dr. Stump to review the progress made. However, I understand that this may result in a flood of email notifications for you. Therefore, I would like to discuss with you if this poses any inconvenience or issues on your end.

I value effective communication and collaboration, and I want to ensure that our ticket management process is efficient for both of us. If you have any concerns or suggestions regarding this matter, please let me know, and I will be more than happy to accommodate your preferences.

Thank you for your understanding.

Best regards,
Alex Guo

**Comment by gg9192** [comment]
What is the problem? 
Currently, there are a lot of spaces that have the all/none buttons. The only category that doesn't have one of these is the subspaces category. Unfortunately, none of the buttons work. In this ticket [here](https://github.com/StarExec/StarExec/pull/349/files) I have made a special js file for everything that deals with selecting bulk items from tables. I will make a new branch from that branch and start working. If we do it from fb1, there will be a merge conflict which can easily be avoided

**Comment by gg9192** [comment]
Here is what needs to be done

- [x] create js function to select all the elements from a table
- [x] create js function to unselect all from a table
- [x] replace the faulty event handlers with the functioning ones

**Comment by gg9192** [comment]
https://github.com/StarExec/StarExec/pull/359

**Comment by vuphan314** [comment]
Alex and Prof. Stump,
Thank you for fixing the All and None buttons!

I did not mind the emails. I could have unsubscribed from notifications for the issue if necessary.

**Comment by gg9192** [comment]
Hello again, the changes that fixed these buttons are live on starexec.org. If the buttons don't work, try clearing the cache, as we developers have had problems with the browser caching the javascript files.

Thanks,
Alex Guo
