### ISSUE TITLE
cannot download job info anymore

### ISSUE THREAD

**Issue by ffrohn** [StarExec/StarExec#312]
Since yesterday, I cannot download job information anymore. Here's a link to one of the affected jobs:

https://www.starexec.org/starexec/secure/details/job.jsp?id=50203

**Comment by astump** [comment]
Hi.  Sorry for this problem.  Could you describe the error more?  Do you get a red 500 page?  Can you attach a screenshot?  We did patch compute nodes yesterday, so there might have been a temporary problem.  Can you confirm the issue is still persisting today (patching is done).

**Comment by ffrohn** [comment]
It was a temporary issue, indeed. Everything works fine again. Thanks!
