### ISSUE TITLE
500s due to esapi logging

### ISSUE THREAD

**Issue by astump** [StarExec/StarExec#313]
In porting off of log4j logging library to logback, I missed that the esapi library needs to be configured to use logback.

**Comment by gg9192** [comment]
A 500 error typically indicates an internal server error, but it's unclear how it specifically relates to ESAPI logging. I have looked at both the tomcat logs (Catalina.out) and the normal logs (Starexec_aguo2.logs). I did not find any error 500s. I have also done grep on all the files in the repo for log4j and didn't find anything aside from log4j being a dependency for star command. Can you please provide me with more information about where the error code 500 is happening?

Our current esapi logger is slf4j. This is clear from src/esapi/ESAPI.properties (ESAPI.Logger=org.owasp.esapi.logging.slf4j.Slf4JLogFactory). Do we just need to change this to use logback?
