### ISSUE TITLE
No "running" status in job pair overview

### ISSUE THREAD

**Issue by ozppupbg** [StarExec/StarExec#314]
Hello!

I recently started using StarExec and was a bit confused, that I did not see a "running" status for my job pairs on the job page - it went directly from "enqueued (2)" to "complete (7)". But if I checked in the pair details, there was a state "running".

I dug a bit into the source code and I think I located the cause of this issue:
https://github.com/StarExec/StarExec/blob/f008917bd453da3f34603bfeaca677077ee0f277/src/org/starexec/config/sge/functions.bash#L506-L514

It updates only the pair status, but not the stage status!

My suggested solution would be along these lines:
``` 
function sendNode { 
 	local NODE=$(dbEscape $1) 
 	local SANDBOX=$(($2)) 
 	log "sending Node Id $NODE to $REPORT_HOST in sandbox $SANDBOX" 
	sendStatus $STATUS_RUNNING
	sendStageStatus $STATUS_RUNNING ${STAGE_NUMBERS[STAGE_INDEX]}
 	dbExec " 
 		CALL UpdateNodeId($PAIR_ID, '$NODE', $SANDBOX); 
 	" 
 } 
```

Regards,

Jan

**Comment by astump** [comment]
Thanks for pointing this out, Jan!  And for your dive into the code.  :-)
I am hoping to have an undergrad developer for the summer, and this would
be a good starter task for that person.
Aaron

**Comment by astump** [comment]
We fixed this recently.  Thanks again for raising this issue.
