### ISSUE TITLE
user guide is behind uiowa VPN?

### ISSUE THREAD

**Issue by jwaldmann** [StarExec/StarExec#318]
On the page https://www.starexec.org/starexec/public/help.jsp (linked at the bottom of each page), when I try to open http://wiki.uiowa.edu/display/stardev/User+Guide, I get https://its.uiowa.edu/node/124846 "The website you were trying to reach is only available on campus or when connected to the VPN."

**Comment by astump** [comment]
Thanks for this bug report.  I was not aware.  University IT has changed something.  I will contact them.

**Comment by astump** [comment]
A pdf version of the user guide is now available outside the VPN.  Thank you very much for bringing the problem to my attention.
