### ISSUE TITLE
Is StarExec down?

### ISSUE THREAD

**Issue by disteph** [StarExec/StarExec#322]
Apologies for raising this on github (I don't see on the StarExec Support page a more appropriate place to raise this).
At the moment the space explorer does not show me anything below the root node (whether I'm logged in or logged out).

**Comment by disteph** [comment]
It's just back up. Apologies for the noise.

**Comment by astump** [comment]
It is ok.  It could be due to load on the head node.

J'espère que tous va bien avec vous, Stéphane!
