### ISSUE TITLE
throws a non-descriptive error when you try to create a job in a subspace that doesn't have any benchmarks 

### ISSUE THREAD

**Issue by presdodd** [StarExec/StarExec#330]
If you try to create a job on benchmarks that don't exist, it tries to let you do so and then throws a vague error. The error it logs is also unhelpful. The same thing happens if you try to run a solver that doesn't have any configurations. 

(e.g. running "run and keep hierarchy structure" in a space that doesn't contain any benchmarks, even if its own subspaces have benchmarks)

**Comment by gg9192** [comment]
- [x] Fix the bug where users create jobs on benchmarks that don't exist
- [x] Fix the bug where users try to run job on solver without configs: https://iowa-my.sharepoint.com/:v:/g/personal/aguo2_uiowa_edu/EQq6axQlHI1CsEmU3U72S10BEEcW2r-UcxiJthitPYNCNg?e=kOIP6i

**Comment by gg9192** [comment]
running solver without configs has been fixed: https://iowa-my.sharepoint.com/:v:/g/personal/aguo2_uiowa_edu/EU-bNqUH8x9LgiFNl8Ol1IMB6bZVP-G9YvY34p29Hrb28w?e=TSa3Re
