### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by astump** [StarExec/StarExec#353]
Add a feature to the Admin section to put the system in read-only mode.  In this mode, jobs cannot be run.  The button to create a job should link to a page that just says the system is closed for running jobs.  The backend code should not allow jobs to be created if the system is in read-only mode.  (Note that having the backend check for this is not redundant, as potentially the frontend could be bypassed.)

**Comment by gg9192** [comment]
Problem decomposition: 

- [x] Create a place on Admin/StarExec for read-only
- [x] create API call that sets this,
- [x] Create SQL procedure to set the read-Only
- [x] create helper function for api
- [x] create function to get the value if readonly mode
- [x] create SQL to get the readonly
- [x] make the addjob redirect if it's readMode
- [x] make an API call to get readOnly
- [x] make front end UI responsive to backend
- [x] make the backend for submit job verify readonly before submitting a job

**Comment by gg9192** [comment]
Note that read_only col has been added to system_flags table

**Comment by gg9192** [comment]
PR is up
