### ISSUE TITLE
Handling extra output more efficiently in jobscript

### ISSUE THREAD

**Issue by astump** [StarExec/StarExec#354]
When solvers run in a pipeline, it can happen that one stage produces output that is supposed to be preserved for benefit of a subsequent stage.  Right now, the function copyOutputNoStats in

src/org/starexec/config/sge/functions.bash

uses the linux rsync command to copy output that is produced in one stage to $SAVED_PAIR_OTHER_OUTPUT_PATH.

The problem is that we have some tools run in the pipeline for SAT Competition that can produce some enormous output files.  One tool produced a file of .5TB.  We only have 1TB disks on those compute nodes, so if we produce a huge file and then copy it, it will exceed our disk space.

So instead of copying the file, we need to just make sure, somehow, that the file ends up in the right place.  We could maybe do a mv, but I am guessing there was some (good) reason why rsync was chosen previously.  

This issue is to investigate how to handle big files at that point of the process, and arrange for them to be put in the correct directory without copying them.

**Comment by gg9192** [comment]
I am actively researching this issue. Notes are here:

1. We have a bash file called job script, which gets run on the cluster every time someone wants to run a job
2. There are currently 2 functions that rely on this function: copyOutputIncrementally and copyOutput
3. In total, this function is called a total of 4 times in the actual script
4. All variables in bash are global unless the keyword local is used.
5. The function creates 2 directories and copies the output there. 
6. All of the "$$__$$" in the jobscript file are filled in by java at src/org/jobs/JobManager.writeJobScript

**Comment by gg9192** [comment]
Here are benefits of rsync
Both rsync and cp are commonly used commands for file and directory copying in Unix-like operating systems. However, rsync offers several advantages over cp in certain scenarios:

Efficient transfers: rsync is designed to efficiently synchronize files between different locations. It only transfers the portions of files that have changed, making it faster than cp when updating large files or directories.

Resumable transfers: If a file transfer is interrupted, rsync can resume from where it left off. It compares the source and destination files, transferring only the differences, which allows you to resume large file transfers without starting from scratch.

Bandwidth optimization: rsync can optimize bandwidth usage by using compression and only transferring the differences between files. This can be beneficial when transferring files over a slow or limited network connection.

Remote transfers: rsync can perform file transfers over a network, allowing you to copy files between local and remote systems. It supports SSH encryption, making it secure for remote transfers.

Preservation of file attributes: By default, rsync preserves various file attributes such as timestamps, ownership, permissions, and symbolic links. This can be important when maintaining file integrity during transfers.

Selective syncing: rsync provides options to selectively sync files based on various criteria, such as file size, modification time, or inclusion/exclusion patterns. This flexibility allows you to customize the synchronization process according to your specific needs.

**Comment by gg9192** [comment]
Definition of Done?
1. Job details need to be available to the end user after the job is run.
2. no subsequent stages that rely on this output are messed up.

**Comment by gg9192** [comment]
After doing some digging, here's what I believe needs to be done. The entire purpose of the rsync is to copy our output files from "$OUT_DIR/output_files/", to other directories. This needs to be done because at the end of each stage, as well as at the end of every job, the sandbox needs to be cleaned i.e. rm -rf * to prepare for the next stage. I have ran grep on both jobScript and functions.bash for the string "$OUT_DIR/output_files/" (the source directory) and the only places are within the function itself. This means that nothing else depends on the output files being there. I believe the reason that rsync was chosen is because rsync is more versatile than cp. Because nothing depends, on the files being there, we can just use mv.

**Comment by astump** [comment]
Ok, I am good with trying just switching to mv.  It would be good if you
could create an experiment to verify this is working.  That might be a
little challenging, because you would have to create a test pipeline.  That
artifact would be worth saving in itself, so you could add it to some
directory, like maybe a pipeline-test directory within StarExec/.
Thanks,
Aaron

**Comment by gg9192** [comment]
Problem: if I modify the jobscript in the repo, it doesn't change the script submitted to the server.
fix: restarted starexec from admin tab

**Comment by gg9192** [comment]
1st pair of this job is a suitable candidate for testing
https://starexec.org/starexec/secure/details/job.jsp?id=44376

**Comment by gg9192** [comment]
I tested this on both the branch with the mv change, and fb1. Unfortunately, I was unable to see multiple stages of the job. Currently, I am unsure what makes a job have multiple stages.

Fix: https://www.starexec.org/starexec/public/batchJobSchema.xsd

**Comment by gg9192** [comment]
The purpose of this comment is to describe how we will test this. The docs that are referenced are here. https://wiki.uiowa.edu/display/stardev/User+Guide

- [x] create a c program that takes as an arguement a file path. Then print out the files contet with Starexec4ever! \n
- [x] create a benchmark that has the Starexec4ever!
- [x] make a XML file for the job. If we wan't a pipeline, we have to use a job.xml file. The docs state this.
- [x] run the solver and verify the output

**Comment by gg9192** [comment]
Now, we just need to write docs for the new pipeline and verify that the mv changes didn't break anything
