### ISSUE TITLE
run script error in termCOMP (test run)

### ISSUE THREAD

**Issue by AkihisaYamada** [StarExec/StarExec#382]
Hi!

we encounter some run script errors, e.g.
https://www.starexec.org/starexec/secure/details/pair.jsp?id=614983478
https://www.starexec.org/starexec/secure/details/pair.jsp?id=614983626

This is speculation by @jwaldmann:
> permission problems on execution host n011
> 
> (I was randomly clicking on "job log" of errors,
> all showed this host)
> 
> perhaps Aaron can re-start this machine,
> or remove it from the queue.

**Comment by astump** [comment]
Sorry for this problem.  I removed n011 from termcomp.q for now.  We had a power outage and UPS failure Thursday or so that left the system in a somewhat broken state.  We have restored things now, so we expect everything should run ok now.  Please let me know if you encounter other problems.

**Comment by AkihisaYamada** [comment]
Thank you! I don't see the problem any more :)
