### ISSUE TITLE
How to add description to solver configuration?

### ISSUE THREAD

**Issue by vuphan314** [StarExec/StarExec#388]
The description of a solver can be specified by including the file `starexec_description.txt`.

But how can the description of a solver *configuration* be specified?

Example:
![image](https://github.com/StarExec/StarExec/assets/12940605/dd5eafff-4c05-4993-8111-8f2aef931dfe)
https://www.starexec.org/starexec/secure/details/solver.jsp?id=47206

**Comment by astump** [comment]
Hello, Vu Phan.

Sadly, the code does not support adding descriptions for configurations upon upload.  Once a configuration is uploaded, or if you create one manually on the site, then you can edit the description there.

Aaron
