### ISSUE TITLE
All job benchmark-configuration pairs fail with "No such file or directory" message

### ISSUE THREAD

**Issue by karkon314** [StarExec/StarExec#389]
Since the last OS change all my jobs fail with "No such file or directory" message for all job benchmark-configuration pairs. The problem occurs even with solvers and benchmarks that worked perfectly before the OS change. The problem occurs with both runsolver and BenchExec benchmarking frameworks. The jobs are launched with setting profile TPTP and post processor SZS (174).

The relevant job log messages for a job running in the runsolver framework are:

> 07/01/24 05:43:52 PM CDT: copying solver: Doing safeCpAll on /export/starexec/solvercache/2024-06-27 17:34:22.0/47568 to /export/starexec/sandbox/solver
07/01/24 05:43:52 PM CDT: solver copy complete
07/01/24 05:43:52 PM CDT: chmod gu+rwx on the solver directory on the execution host (/export/starexec/sandbox/solver)
...
07/01/24 05:43:52 PM CDT: copying benchmark /home/starexec/Benchmarks/1217/20240627-17.38.52.683/ALG215+3.p to /export/starexec/sandbox/benchmark/theBenchmark.p on execution host...
07/01/24 05:43:52 PM CDT: benchmark copy complete
07/01/24 05:43:52 PM CDT: execution host solver configuration verified
07/01/24 05:43:52 PM CDT: execution host benchmark verified
07/01/24 05:43:52 PM CDT: sandboxing workspace with first sandbox user
07/01/24 05:43:52 PM CDT: listing contents of sandbox...
...
/export/starexec/sandbox/benchmark:
total 1880
-rwxr-xr-x 1 tomcat star-dev 1924505 Jul  1 17:43 theBenchmark.p
...
/export/starexec/sandbox/solver/bin:
total 12076
-rwxrwx--x 1 sandbox star-dev 1463984 Jul  1 17:43 drodi
-rwxrwx--x 1 sandbox star-dev 6254136 Jul  1 17:43 drodi.lrn
-rwxr-x--- 1 sandbox star-dev  114628 Jul  1 17:43 runsolver
-rwxrwx--x 1 sandbox star-dev     773 Jul  1 17:43 starexec_run_config1
...
0.00/0.00	exec failed: No such file or directory
0.00/0.00	Solver command line was: /export/starexec/sandbox/solver/bin/starexec_run_config1 /export/starexec/sandbox/benchmark/theBenchmark.p /export/starexec/sandbox/output/output_files

The job log shows that both the solver and benchmark files are correctly copied. However when the solver command is issued the configuration script starexec_run_config1 is not found.

Any help will be appreciated.

**Comment by jwaldmann** [comment]
Hard to debug from a distance. Different kernel, different libc version, ... does your program work in the VM provided by starexec? Are you providing an executable, or are you calling some interpreter, if so, for what language. - For my executable (for termination competition), I found it quite helpful to execute `ldd $my-exe` [on starexec ] to find what .so-files I should include.

**Comment by karkon314** [comment]
@jwaldmann I am providing an executable. Mi program is written in C and statically linked so it doesn't need any .so files. Executing `ldd $my-exe` reports `not a dynamic executable`.

To my knowledge my program doesn't run in the VM and in fact I was not aware of that possibility. The compiled executable is included in the solver itself and is called directly from the configuration script starexec_run_config1. It is the
`drodi`  file reported in the job log part that I included previously.

Where can I find documentation on how to use the VM provided by starexec?

Many thanks in advance.

**Comment by karkon314** [comment]
@jwaldmann To be more specific the configuration file is a script file written in Tcsh, not in the standard bash command interpreter. The C program is called from this script file. It may be that the Tcsh bash is not available after the OS change. I will try the bash command interpreter and post the results.

**Comment by jwaldmann** [comment]
[vm spec] Before the update, starexec provided a vm image for download. I no longer find it. Its spec was https://www.starexec.org/starexec/public/machine-specs.txt but this is obsolete. I guess the best we currently have is https://github.com/StarExec/StarExec/issues/386#issuecomment-2161046533 . I infer it is 
Ubuntu 22.04

yes `tcsh` might be a reason. I have locally a machine with a default installation of Ubuntu 22.04.4 LTS, and it has not tcsh.

**Comment by karkon314** [comment]
@jwaldmann Yes, `tcsh` is the reason. It works with bash command interpreter, therefore I will close the issue.

Anyway it would be fine to have tcsh command interpreter installed. It was installed before the OS change and the SZS (174) post processor also fails and I guess that the reason is that it uses tcsh.

Many thanks for your support.

**Comment by karkon314** [comment]
The problem is caused because tcsh command interpreter is not installed. It was installed before the OS change. The SZS (174) post processor also fails and I guess that the reason is that it uses tcsh. The bash command interpreter works fine so I close the issue but it would be fine to have tcsh command interpreter installed so that SZS post processor can be used again.

**Comment by jwaldmann** [comment]
glad to have helped.

>  it would be fine to have tcsh ...

then open an issue, with a descriptive title.

**Comment by astump** [comment]
We should be able to install tcsh if there is a need for it.  Please confirm (yes, opening a new issue would be good confirmation.)
