### ISSUE TITLE
Queues are offline

### ISSUE THREAD

**Issue by fabeulous** [StarExec/StarExec#391]
There seems to be an issue with the queues currently. When creating a Job no queue can be selected, and the 'Cluster Status' page lists a single queue called `error: commlib error: got select error (Connection refused) `.

**Comment by astump** [comment]
Oh, thanks for that report.  Yes, I see this, too.  It is a national holiday in the US today, so I am not sure it will get fixed until tomorrow (July 5th).  Very sorry for the inconvenience.

**Comment by fabeulous** [comment]
Thanks for your quick reply despite the holiday. Then I'll probably just have to wait for tomorrow.

**Comment by ddholstad99** [comment]
The queues should be back online now

**Comment by fabeulous** [comment]
Thanks @ddholstad99 ! It's all working again for me.
